const defaultSettings = {
	master: true,
	performance: "manual",
	advancedSettings: {
		Log_Groups: {
			title: "Log groups",
			words: [
				{
					enabled: true,
					code: 31,
					word: "error",
					color: "rgba(155, 0, 0, 0.44)",
					backgroundColor: "rgba(155, 0, 0, 0.44)",
					emoji: "❌",
					label: "Error",
				},
				{
					enabled: true,
					code: 33,
					word: "warn",
					color: "rgba(227, 217, 0, 0.4)",
					backgroundColor: "rgba(227, 217, 0, 0.4)",
					emoji: "⚠️",
					label: "Warn",
				},
				{
					enabled: true,
					code: 32,
					word: "info",
					color: "rgba(0, 155, 10, 0.16)",
					backgroundColor: "rgba(0, 155, 10, 0.16)",
					emoji: "ℹ️",
					label: "Info",
				},
				{
					enabled: true,
					code: 34,
					word: "debug",
					color: "rgba(0, 78, 155, 0.16)",
					backgroundColor: "rgba(0, 78, 155, 0.16)",
					emoji: "🐛",
					label: "Debug",
				},
			],
			id: "Log_Groups",
			switch: true,
			isAvailable: true,
			wantBackground: true,
		},
		Log_Tails: {
			title: "Log Tails",
			words: [
				{
					enabled: true,
					code: 31,
					word: "error",
					color: "rgba(155, 0, 0, 0.44)",
					backgroundColor: "rgba(155, 0, 0, 0.44)",
					emoji: "❌",
					label: "Error",
				},
				{
					enabled: true,
					code: 33,
					word: "warn",
					color: "rgba(227, 217, 0, 0.4)",
					backgroundColor: "rgba(227, 217, 0, 0.4)",
					emoji: "⚠️",
					label: "Warn",
				},
				{
					enabled: true,
					code: 32,
					word: "info",
					color: "rgba(0, 155, 10, 0.16)",
					backgroundColor: "rgba(0, 155, 10, 0.16)",
					emoji: "ℹ️",
					label: "Info",
				},
				{
					enabled: true,
					code: 34,
					word: "debug",
					color: "rgba(0, 78, 155, 0.16)",
					backgroundColor: "rgba(0, 78, 155, 0.16)",
					emoji: "🐛",
					label: "Debug",
				},
			],
			id: "Log_Tails",
			switch: false,
			isAvailable: false,
			wantBackground: true,
		},
		Log_Insights: {
			title: "Log Insights",
			words: [
				{
					enabled: true,
					code: 31,
					word: "error",
					color: "rgba(155, 0, 0, 0.44)",
					backgroundColor: "rgba(155, 0, 0, 0.44)",
					emoji: "❌",
					label: "Error",
				},
				{
					enabled: true,
					code: 33,
					word: "warn",
					color: "rgba(227, 217, 0, 0.4)",
					backgroundColor: "rgba(227, 217, 0, 0.4)",
					emoji: "⚠️",
					label: "Warn",
				},
				{
					enabled: true,
					code: 32,
					word: "info",
					color: "rgba(0, 155, 10, 0.16)",
					backgroundColor: "rgba(0, 155, 10, 0.16)",
					emoji: "ℹ️",
					label: "Info",
				},
				{
					enabled: true,
					code: 34,
					word: "debug",
					color: "rgba(0, 78, 155, 0.16)",
					backgroundColor: "rgba(0, 78, 155, 0.16)",
					emoji: "🐛",
					label: "Debug",
				},
			],
			id: "Log_Insights",
			switch: true,
			isAvailable: true,
			wantBackground: true,
		},
	},
};

export default defaultSettings;
