on:
    push:
        tags:
            - "*"

name: Auto-release pipeline

jobs:
    build:
        name: build-prod-pipeline
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v4
            - name: Getting Node.js version from .nvmrc
              run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
              id: nvm
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "${{ steps.nvm.outputs.NVMRC }}"
            - name: Install dependencies
              run: npm install
            - name: Build project
              run: npm run build
            - name: Zip distribution folder
              run: zip aws-cloudwatch-colorize.zip dist -r
            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  prerelease: false
                  files: aws-cloudwatch-colorize.zip
